version: '3'
services:
  influxdb:
    image: influxdb:2.0.7
    ports:
      - "8086:8086"
  # Use the influx cli to set up an influxdb instance.
  influxdb_cli:
    links:
      - influxdb
    image: influxdb:2.0.7
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    depends_on:
      - influxdb
  telegraf:
    image: telegraf
    links:
      - influxdb
    env_file:
      - ./influxv2.env
    depends_on:
      - influxdb_cli
volumes:
  influxdbv2: